### ISSUE TITLE
riak_get: objects in riak_get_response have no bucket/key

### ISSUE THREAD

**Issue by jrwest** [basho-labs/riak-c-client#15]
Result of printing the object returned from `riak_get`. This seems to be because `RpbGetResp` does not include this information so `riak_decode_get_response` does not fill in the information.

```
V-Clock: 6bce61606060cc604a6160492d4e2dcc60ca63657801146206d27c375e9fe6cb0200
Unmodified: false
Deleted: false
Objects: 1
Bucket:
Value: 123
Last Mod: 2013-11-04 00:34:22
Last Mod uSecs: 340166
VTag: 5iVpqDzLUuRkQwm1aWl7eF
```

NOTE: I assume something similar occurs in the async interface but I haven't tested it myself.

**Comment by hazen** [comment]
Yes, we just dump what we get back in the message.  I talked to Roach a while back and he says Java caches those values, which I guess we'll have to do on our side as well.  Needs to be stuffed into the event/context.
