### ISSUE TITLE
Update riak-pb to Generate C Headers

### ISSUE THREAD

**Issue by hazen** [basho-labs/riak-c-client#17]
Let me know if this is a bad idea, but seems consistent with the other clients.

**Comment by bookshelfdave** [comment]
+1

**Comment by hazen** [comment]
The generation of PB headers is taken care of by https://github.com/basho/riak_pb/pull/70 . Now we just need to tweak the riak_c_client Makefile to use these headers/source files instead of using the `.proto` files this repo.
