### ISSUE TITLE
logging (w/o zlog) should not assume stderr is open

### ISSUE THREAD

**Issue by jrwest** [basho-labs/riak-c-client#19]
zlog is configurable so its not really my concern. However, https://github.com/basho/riak-c-client/blob/develop/src/riak_log.c#L75 would cause a problem for daemons for example

**Comment by hazen** [comment]
@jrwest Where should output go then, if stderr is closed?

**Comment by jrwest** [comment]
I think by default it shouldn't log anywhere :). I haven't looked at the recent logging changes, but if I haven't added logging, the client shouldn't try to output to any stream.

**Comment by hazen** [comment]
Cool.  #21 Took care of this.  We really only use stderr for the example program to complain to the user.  Right now the default does nothing.

**Comment by hazen** [comment]
Please reopen if I misunderstood

**Comment by jrwest** [comment]
That wfm. Basically, my concern was exactly that: the logging was mostly useful for `example.c` and not elsewhere. 

CLARIFICATION: I didn't mean _all logging_, just that fallback logging this issue mentions.
