### ISSUE TITLE
Doesn't build neatly on Ubuntu 12.04

### ISSUE THREAD

**Issue by bkerley** [basho-labs/riak-c-client#35]
libprotobuf-c doesn't install a pkg-config file on Debian or Ubuntu 12.04: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=731726

A file that works but isn't proper is as follows:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/google/protobuf-c

Name: Protocol Buffers
Description: Google's Data Interchange Format
Version: 2.4.1
Libs: -L${libdir} -lprotobuf-c -lz  -pthread  -lpthread
Cflags: -I${includedir} -pthread
# Commented out because it crashes pkg-config *sigh*:
#   http://bugs.freedesktop.org/show_bug.cgi?id=13265
# Conflicts: protobuf-lite
```

**Comment by hazen** [comment]
I built `protobuf-c` from scratch and it does create a `.pc` file.  Since this is a Debian packaging issue, is there anything we can do about it on our end?

**Comment by hazen** [comment]
Updated the `README.md` in #42 to basically build your own on Ubuntu.  There is a version conflict on 13.10, too, so having your own version is saferer.
