### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by bachpedersen** [basho-labs/riak-c-client#36]
Hi
Nice work so far!

A little comment about the build:
It is not easy getting the client to build, and not sure how to get the tests to run .. will probably figure it out, however a build system like cmake or even scons(you seem to have discontinued this for some reason?).

Plain autotools is ruling windows out and the current state of the build is not good (if you make install some of the headers will not be included etc.)

If you are sticking with autotool a small guide to runnings tests etc would be nice.

**Comment by bachpedersen** [comment]
Found the tests solution in one of the closed issue, still think documentation or build system would be nice

**Comment by hazen** [comment]
We had started with Scons, but thought autotools might be more universal in Unix-land for C projects. I think `make install` has some issues right now, anyway.

**Comment by bachpedersen** [comment]
Reading between the lines there will never be windows support?
I know windows C is old etc etc. but it is really not that much extra work to make it compile.

**Comment by hazen** [comment]
Sorry for the confusion, @TriKaspar.  For the time being we are going to focus on POSIX systems for the C client.  We may in the future add Windows support if there is community demand for it.  Take a look at #42 for the latest updated build instructions.

Please reopen (or create a new one) if you still have issues or concerns.
